{{- if .Values.templates.bilateralSettlement -}}

apiVersion: mojaloop.io/v1
kind: MojaloopReport
metadata:
  name: report-bilateral-settlement
  {{ include "common.annotations" . | nindent 2 }}
spec:
  endpoint:
    params:
      - name: settlementId
        required: true
    path: /report-bilateral-settlement
  permission: transferApi
  queries:
    - name: settlementInfoResult
      query: >
        SELECT
            s.settlementId,
            s.createdDate,
            ssc.settlementStateId as currenctState,
            ssc.createdDate as lastStateUpdate,
            sSW.createdDate as windowCreatedDate,
            sSW.settlementWindowId,
            MIN(sWSCOpen.createdDate) as windowOpenDate,
            MAX(sWSCClosed.createdDate) as windowClosedDate
        FROM settlement s
        INNER JOIN settlementSettlementWindow sSW
                on s.settlementId = sSW.settlementId
        INNER JOIN settlementWindowStateChange sWSCOpen
                on sSW.settlementWindowId = sWSCOpen.settlementWindowId AND sWSCOpen.settlementWindowStateId = 'OPEN'
        INNER JOIN settlementWindowStateChange sWSCClosed
                on sSW.settlementWindowId = sWSCClosed.settlementWindowId AND sWSCClosed.settlementWindowStateId = 'CLOSED'
        INNER JOIN settlementStateChange ssc
            on s.currentStateChangeId = ssc.settlementStateChangeId
        WHERE s.settlementId = :settlementId
        GROUP BY s.settlementId, sSW.settlementWindowId;
    - name: settlementParticipantCurrencyIdsResult
      query: >
        SELECT
            result1.participantCurrencyId as debtorParticipantCurrencyId,
            result2.participantCurrencyId as creditorParticipantCurrencyId,
            SUM(result1.amount) as debtorTotalAmount,
            SUM(result2.amount) as creditorTotalAmount
        FROM

        (SELECT
            pc.participantCurrencyId,
            unioned.transferId,
            unioned.uniqueLegId,
            SUM(unioned.change) as amount
        FROM (
            SELECT
                ppc.participantCurrencyId,
                ppc.change,
                tf.settlementWindowId,
                tf.transferId AS transferId,
                tf.transferId AS uniqueLegId
            FROM
                transferFulfilment AS tf
            INNER JOIN
                transferStateChange AS tsc
                ON tsc.transferId = tf.transferId
            INNER JOIN
                participantPositionChange AS ppc
                ON ppc.transferStateChangeId = tsc.transferStateChangeId
            INNER JOIN
                settlementParticipantCurrency AS spc
                ON ppc.participantCurrencyId = spc.participantCurrencyId AND spc.settlementId = :settlementId
            INNER JOIN
                settlementSettlementWindow ssw
                ON tf.settlementWindowId = ssw.settlementWindowId AND ssw.settlementId = :settlementId

            UNION ALL

            SELECT
                ppc.participantCurrencyId,
                ppc.change,
                fxtf.settlementWindowId,
                fxt1.determiningTransferId AS transferId,
                fxt1.commitRequestId AS uniqueLegId
            FROM
                fxTransferFulfilment AS fxtf
            INNER JOIN
                fxTransfer AS fxt1
                ON fxt1.commitRequestId = fxtf.commitRequestId
            INNER JOIN
                fxTransferStateChange AS fxtsc
                ON fxtsc.commitRequestId = fxtf.commitRequestId
            INNER JOIN
                participantPositionChange AS ppc
                ON ppc.fxTransferStateChangeId = fxtsc.fxTransferStateChangeId
            INNER JOIN
                settlementParticipantCurrency AS spc
                ON ppc.participantCurrencyId = spc.participantCurrencyId AND spc.settlementId = :settlementId
            INNER JOIN
                settlementSettlementWindow ssw
                ON fxtf.settlementWindowId = ssw.settlementWindowId AND ssw.settlementId = :settlementId
        ) AS unioned
        INNER JOIN
            participantCurrency AS pc
            ON pc.participantCurrencyId = unioned.participantCurrencyId
        WHERE unioned.change > 0
        GROUP BY
            pc.participantCurrencyId,
            unioned.transferId,
            unioned.uniqueLegId
        ORDER BY unioned.transferId
        ) as result1

        INNER JOIN

        (SELECT
            pc.participantCurrencyId,
            unioned.transferId,
            unioned.uniqueLegId,
            SUM(unioned.change) as amount
        FROM (
            SELECT
                ppc.participantCurrencyId,
                ppc.change,
                tf.settlementWindowId,
                tf.transferId AS transferId,
                tf.transferId AS uniqueLegId
            FROM
                transferFulfilment AS tf
            INNER JOIN
                transferStateChange AS tsc
                ON tsc.transferId = tf.transferId
            INNER JOIN
                participantPositionChange AS ppc
                ON ppc.transferStateChangeId = tsc.transferStateChangeId
            INNER JOIN
                settlementParticipantCurrency AS spc
                ON ppc.participantCurrencyId = spc.participantCurrencyId AND spc.settlementId = :settlementId
            INNER JOIN
                settlementSettlementWindow ssw
                ON tf.settlementWindowId = ssw.settlementWindowId AND ssw.settlementId = :settlementId

            UNION ALL

            SELECT
                ppc.participantCurrencyId,
                ppc.change,
                fxtf.settlementWindowId,
                fxt1.determiningTransferId AS transferId,
                fxt1.commitRequestId AS uniqueLegId
            FROM
                fxTransferFulfilment AS fxtf
            INNER JOIN
                fxTransfer AS fxt1
                ON fxt1.commitRequestId = fxtf.commitRequestId
            INNER JOIN
                fxTransferStateChange AS fxtsc
                ON fxtsc.commitRequestId = fxtf.commitRequestId
            INNER JOIN
                participantPositionChange AS ppc
                ON ppc.fxTransferStateChangeId = fxtsc.fxTransferStateChangeId
            INNER JOIN
                settlementParticipantCurrency AS spc
                ON ppc.participantCurrencyId = spc.participantCurrencyId AND spc.settlementId = :settlementId
            INNER JOIN
                settlementSettlementWindow ssw
                ON fxtf.settlementWindowId = ssw.settlementWindowId AND ssw.settlementId = :settlementId
        ) AS unioned
        INNER JOIN
            participantCurrency AS pc
            ON pc.participantCurrencyId = unioned.participantCurrencyId
        WHERE unioned.change < 0
        GROUP BY
            pc.participantCurrencyId,
            unioned.transferId,
            unioned.uniqueLegId
        ORDER BY unioned.transferId
        ) as result2

        ON result1.transferId = result2.transferId AND result1.uniqueLegId = result2.uniqueLegId

        GROUP BY result1.participantCurrencyId, result2.participantCurrencyId;
    - name: allParticipantCurrencyIds
      query: >
        SELECT
          pc.participantCurrencyId,
          pc.participantId,
          pc.currencyId,
          p.name,
          p.description,
          p.isProxy
        FROM participantCurrency AS pc
        INNER JOIN
            participant AS p
            ON pc.participantId = p.participantId
        ORDER BY pc.participantCurrencyId;
  template: |
    <!DOCTYPE html>
    <html lang="en">

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>DRPP Bilateral Settlement Report</title>
        <style>
            body {
                font-family: 'Arial', sans-serif;
                background-color: #f5f5f5;
                margin: 0;
                padding: 20px;
                color: #333;
            }

            .container {
                max-width: 100%;
                margin: 0 auto;
                background-color: #fff;
                padding: 20px;
                box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
            }

            .grid-container {
                display: grid;
                grid-template-columns: repeat(2, 1fr);
                gap: 20px;
            }

            .grid-block {
                padding: 2px;
                border-radius: 8px;
            }

            .header {
                display: flex;
                justify-content: space-between;
                align-items: center;
                border-bottom: 2px solid #00447c;
                padding-bottom: 10px;
            }

            .header h1 {
                margin: 0;
                color: #00447c;
                font-size: 24px;
            }

            .header img {
                max-height: 50px;
            }

            .summary {
                margin-top: 20px;
                padding: 15px;
                background-color: #e9f3fa;
                border-left: 6px solid #00447c;
                border-radius: 5px;
                box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
                max-width: 500px;
            }

            .summary p {
                margin: 5px 0;
                font-weight: bold;
            }

            table {
                width: 100%;
                border-collapse: collapse;
                margin-top: 20px;
            }

            table, th, td {
                border: 1px solid #ddd;
            }

            th {
                background-color: #00447c;
                color: #fff;
                padding: 10px;
                font-size: 1.0em;
            }

            td {
                line-height: 1.6;
                padding: 10px;
                text-align: left;
                font-size: 0.9em;
            }

            tr:nth-child(even) {
                background-color: #f2f2f2;
            }

            .smallFont {
                font-size: 0.7em;
            }

            .thStyle {
                background-color: #00447c;
                color: #fff;
                padding: 10px;
                font-size: 1.0em;
            }

            .button-link {
                display: inline-block;
                padding: 10px 20px;
                font-size: 16px;
                color: #fff;
                background-color: #007bff;
                text-decoration: none;
                border-radius: 5px;
                transition: background-color 0.3s, transform 0.2s;
                font-weight: 500;
                box-shadow: 0 4px 8px rgba(0, 123, 255, 0.2);
            }

            .button-link:hover {
                background-color: #0056b3;
                transform: translateY(-2px);
                box-shadow: 0 6px 12px rgba(0, 86, 179, 0.3);
            }

            .button-link:active {
                transform: translateY(0);
                box-shadow: 0 4px 8px rgba(0, 86, 179, 0.2);
            }

            .highlight-link {
                color: #007bff;
                text-decoration: none;
                padding: 3px 5px;
                border-radius: 3px;
                transition: background-color 0.2s, color 0.2s;
            }

            .highlight-link:hover {
                background-color: #00447c;
                color: white;
            }

            .footer {
                margin-top: 20px;
                text-align: center;
                font-size: 0.9em;
                color: #666;
            }

            .footer p {
                margin: 5px 0;
            }
        </style>
    </head>

    <%
        function calculateNetSettlement(input) {
            // A map to track transactions for easy lookup
            const transactionsMap = new Map();

            // Helper function to generate unique keys for debtor and creditor pairs
            function generateKey(debtorId, creditorId) {
                return `${debtorId}_${creditorId}`;
            }

            // Process the input transactions
            input.forEach(transaction => {
                const { debtorParticipantCurrencyId, creditorParticipantCurrencyId, debtorTotalAmount } = transaction;
                const key = generateKey(debtorParticipantCurrencyId, creditorParticipantCurrencyId);

                // Store transaction in the map
                if (!transactionsMap.has(key)) {
                    transactionsMap.set(key, {
                        netDebtor: debtorParticipantCurrencyId,
                        netCreditor: creditorParticipantCurrencyId,
                        totalAmountSent: parseFloat(debtorTotalAmount),
                        totalReverseAmount: 0
                    });
                } else {
                    transactionsMap.get(key).totalAmountSent += parseFloat(debtorTotalAmount);
                }

                // Check for a reverse transaction
                const reverseKey = generateKey(creditorParticipantCurrencyId, debtorParticipantCurrencyId);
                if (transactionsMap.has(reverseKey)) {
                    if (transactionsMap.get(reverseKey).totalAmountSent >= parseFloat(debtorTotalAmount)) {
                        // Update reverse amount for the original transaction
                        transactionsMap.get(reverseKey).totalReverseAmount -= parseFloat(debtorTotalAmount);
                        transactionsMap.delete(key);
                    } else {
                        // Update reverse amount for the original transaction
                        transactionsMap.get(key).totalReverseAmount = -transactionsMap.get(reverseKey).totalAmountSent;
                        transactionsMap.delete(reverseKey);
                    }
                }
            });

            // Calculate net settlement amount and format the output
            const output = [];
            transactionsMap.forEach(transaction => {
                const { netDebtor, netCreditor, totalAmountSent, totalReverseAmount } = transaction;
                const netSettlementAmount = totalAmountSent + totalReverseAmount;
                output.push({
                    netDebtor,
                    netCreditor,
                    totalAmountSent: totalAmountSent,
                    totalReverseAmount: totalReverseAmount,
                    netSettlementAmount
                });
            });

            return output;
        }


      const calculatedSettlementRows = calculateNetSettlement(settlementParticipantCurrencyIdsResult)

      const calculatedSettlementRowsWithDetails = calculatedSettlementRows.map((calculatedSettlementRow) => {
        const debtorParticipantCurrencyId = calculatedSettlementRow.netDebtor;
        const creditorParticipantCurrencyId = calculatedSettlementRow.netCreditor;
        const payerParticipantCurrencyDetails = allParticipantCurrencyIds.find((participantCurrencyId) => participantCurrencyId.participantCurrencyId === debtorParticipantCurrencyId);
        const payeeParticipantCurrencyDetails = allParticipantCurrencyIds.find((participantCurrencyId) => participantCurrencyId.participantCurrencyId === creditorParticipantCurrencyId);
        return {
          ...calculatedSettlementRow,
          payerParticipantCurrencyDetails,
          payeeParticipantCurrencyDetails
        };
      });

      const settlementInfo = settlementInfoResult[0];
      const dataForJson = {
        settlementInfo,
        calculatedSettlementRowsWithDetails
      }
    %>

    <body data-json="<%= JSON.stringify(dataForJson) %>" >
        <div class="container">
            <div class="header">
                <h1>DRPP Bilateral Net Settlement Report</h1>
                <img src="" alt="Logo">
            </div>

            <div class="summary">
                <p>Settlement ID: <%= settlementInfo?.settlementId %></p>
                <p>State: <%= settlementInfo?.currenctState %></p>
                <p>Earliest Window Start: <%= settlementInfo?.windowOpenDate.toISOString() %></p>
                <p>Latest Window Finish: <%= settlementInfo?.windowClosedDate.toISOString() %></p>
                <p>Created Date: <%= settlementInfo?.createdDate.toISOString() %></p>
                <p>Last State Update: <%= settlementInfo?.lastStateUpdate.toISOString() %></p>
            </div>

                  <table cellpadding='0' cellspacing='0'>
                      <tbody>
                      <tr>
                        <th>Net Debtor</th>
                        <th>Net Creditor</th>
                        <th>Currency</th>
                        <th>Total Sent Amount</th>
                        <th>Total Received Amount</th>
                        <th>Net Settlement Amount</th>
                      </tr>
                      <% for(let sd of calculatedSettlementRowsWithDetails) { %>
                      <tr>
                        <td><%= sd.payerParticipantCurrencyDetails.name %></td>
                        <td><%= sd.payeeParticipantCurrencyDetails.name %></td>
                        <td><%= sd.payeeParticipantCurrencyDetails.currencyId %></td>
                        <td><%= sd.totalAmountSent %></td>
                        <td><%= sd.totalReverseAmount >= 0 ? `${sd.totalReverseAmount}` : `(${-sd.totalReverseAmount})` %></td>
                        <td><%= sd.netSettlementAmount %></td>
                      </tr>
                      <% } %>
                  </table>
            <!--<div class="grid-container">
                <div class="grid-block">
                </div>
            </div>-->

            <div class="footer">
                <p>Generated on: <%= (new Date()).toUTCString() %></p>
            </div>
        </div>

    </body>
    </html>

{{- end }}
